Repository Xtreme-Thinkers/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#9 Added GUI for password manager
  password-manager/GUI.py
  password-manager/logo.png
Labels: hacktoberfest, hacktoberfest-accepted

#13 tax calculator problem statement
  tax-calculator/README.md
  tax-calculator/tax calculator problem statement.pdf
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#17 Added the readme for the tax calculation process
  tax-calculator/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 updated the chenethasantha documentation
  chenethasantha/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#19 data-scraper
  data-scraper/README.md
  data-scraper/main.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#23 Added HTML,CSS,JAVASCRIPT - Drawing_app
  Drawing_app/index.html
  Drawing_app/script.js
  Drawing_app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#26 added update function.
  password-manager/data.json
  password-manager/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#22 updated main.py
  data-scraper/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#28 Data scraper with fake user agent
  data-scraper/data-scraper-with-fake-agent/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#34 Need some fix in the Drawing App #Isuue_fixed
  Drawing_app/README (1).md
  Drawing_app/images/2.jpg
  Drawing_app/images/updated_drawingapp.jpg
  Drawing_app/index.html
  Drawing_app/script.js
  Drawing_app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#43 react feedback-app with tailwindcdn
  feedback-app/.gitignore
  feedback-app/README.md
  feedback-app/build/asset-manifest.json
  feedback-app/build/favicon.ico
  feedback-app/build/index.html
  feedback-app/build/logo192.png
  feedback-app/build/logo512.png
  feedback-app/build/manifest.json
  feedback-app/build/robots.txt
  feedback-app/build/static/css/main.fa72ae7b.css
  feedback-app/build/static/css/main.fa72ae7b.css.map
  feedback-app/build/static/js/main.1f1f42e3.js
  feedback-app/build/static/js/main.1f1f42e3.js.LICENSE.txt
  feedback-app/build/static/js/main.1f1f42e3.js.map
  feedback-app/db 2.json
  feedback-app/db.json
  feedback-app/package-lock.json
  feedback-app/package.json
  feedback-app/public/favicon.ico
  feedback-app/public/index.html
  feedback-app/public/logo192.png
  feedback-app/public/logo512.png
  feedback-app/public/manifest.json
  feedback-app/public/robots.txt
  feedback-app/src/App.js
  feedback-app/src/components/AboutIconLink.jsx
  feedback-app/src/components/FeedbackForm.jsx
  feedback-app/src/components/FeedbackItem.jsx
  feedback-app/src/components/FeedbackList.jsx
  feedback-app/src/components/FeedbackStats.jsx
  feedback-app/src/components/Header.jsx
  feedback-app/src/components/RatingSelect.jsx
  feedback-app/src/components/assets/spinner.gif
  feedback-app/src/components/shared/.Spinner 2.jsx.icloud
  feedback-app/src/components/shared/Button.jsx
  feedback-app/src/components/shared/Card.jsx
  feedback-app/src/components/shared/Spinner.jsx
  feedback-app/src/context/FeedbackContext.jsx
  feedback-app/src/data/data.js
  feedback-app/src/index.css
  feedback-app/src/index.js
  feedback-app/src/pages/AboutPage.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#32 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added a Calculator
  Calculator/Screenshot 2022-10-08 190754.png
  Calculator/dark.png
  Calculator/index.html
  Calculator/index.js
  Calculator/light.png
  Calculator/readme.md
  Calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#50 added a responsive neomorphic image gallery
  Responsive neomorphic image gallery/frontend/index.html
  Responsive neomorphic image gallery/frontend/style.css
  Responsive neomorphic image gallery/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#49 Updated README.md for feedback application
  feedback-app/README.md
  feedback-app/package-lock.json
  feedback-app/package.json
Labels: hacktoberfest, hacktoberfest-accepted

#58 react-contact-manager
  React_Contact_Manager/package-lock.json
  React_Contact_Manager/package.json
  React_Contact_Manager/public/index.html
  React_Contact_Manager/readme.md
  React_Contact_Manager/src/api/contacts.js
  React_Contact_Manager/src/components/AddContact.js
  React_Contact_Manager/src/components/App.js
  React_Contact_Manager/src/components/ContactCard.js
  React_Contact_Manager/src/components/ContactList.js
  React_Contact_Manager/src/components/EditContact.js
  React_Contact_Manager/src/components/Header.js
  React_Contact_Manager/src/components/Untitled-1.txt
  React_Contact_Manager/src/index.js
  React_Contact_Manager/src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#64 Added sudoku solver program
  Sudoku-solver/sudoku_solver.py
Labels: hacktoberfest, hacktoberfest-accepted

#67 music web app
  music web/README.md
  music web/ek-tarfa-darshan-raval-ringtone-pagalworld-mobi-54938.mp3
  music web/jai-ho-jai-ho-slumdog-millionaire-1-1-54922.mp3
  music web/music1.css
  music web/music1.html
  music web/music1.js
  music web/name.md
  music web/raataan-lambiyan-jubin-nautiyal-54738-54949-1-54963.mp3
  music web/zz.md
Labels: hacktoberfest, hacktoberfest-accepted

#70 Added Etch A Sketch App using Turtle
  Etch A Sketch/Readme.md
  Etch A Sketch/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#72 Added Caesar Cipher Project
  Caesar Cipher/Art.py
  Caesar Cipher/README.md
  Caesar Cipher/img/cc.png
  Caesar Cipher/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#75 Patch 1
  Anime Data/README.md
  Anime Data/package-lock.json
  Anime Data/package.json
  Anime Data/public/favicon.ico
  Anime Data/public/index.html
  Anime Data/public/logo192.png
  Anime Data/public/logo512.png
  Anime Data/public/manifest.json
  Anime Data/public/robots.txt
  Anime Data/src/App.js
  Anime Data/src/anime image api.txt
  Anime Data/src/index.css
  Anime Data/src/index.js
  Anime Data/src/jujutsuKaisen.jpeg
Labels: hacktoberfest, hacktoberfest-accepted

#83 Create python zip file brute forcer
  python zip file brute forcer
Labels: hacktoberfest, hacktoberfest-accepted

#78 local storage and event delegation
  calculator/calc.css
  calculator/calc.html
  calculator/calc.js
  calculator/name.md
  local storage event delegation/event.html
  local storage event delegation/name.md
  local storage event delegation/style.css
  local storage event delegation/style.js
Labels: hacktoberfest, hacktoberfest-accepted

#66 Background Colour Changer Using Javascript
  BackgroundColourChanger/BG_Color_Changer_Using_JS.html
  BackgroundColourChanger/readme.md
Labels: hacktoberfest, hacktoberfest-accepted
